#ifndef TestGPU_AcceleratorService_TestAcceleratorServiceProducerGPUHelpers
#define TestGPU_AcceleratorService_TestAcceleratorServiceProducerGPUHelpers

void TestAcceleratorServiceProducerGPUHelpers_simple_kernel();

#endif
